During make build:

>> SIPing 3 files...
>> /usr/pkg/bin/python3.9 -c from sipbuild.tools.build import main; main(); --verbose --no-make --qmake /usr/pkg/qt5/bin/qmake
>> Querying qmake about your Qt installation...
>> /usr/pkg/qt5/bin/qmake -query
>> These bindings will be built: pictureflow.
>> Generating the pictureflow bindings...
>> -c: Unable to find file "QtWidgets/QtWidgetsmod.sip"

We do have that file, in /usr/pkg/share/sip3.9/PyQt5/QtWidgets/QtWidgetsmod.sip.
This setting likely needs to be adjusted to the new way of sipping/building:
MAKE_ENV+=		SIP_DIR=${BUILDLINK_PREFIX.py-sip}/share/sip${PYVERSSUFFIX}

    (the message comes from sip-6.5.0/code_generator/metasrc/lexer.l; adding a directory to includeDirList somehow might help. The value may come from a call to set_globals. That is called in /sipbuild/builder.py with sip_include_dirs.

    Project() has an option called sip_include_dirs.

    Maybe baking the path into sip6 or pyqtbuild is the thing to do.

Next error:

>> SIPing 3 files...
>> /usr/pkg/bin/python3.9 -c from sipbuild.tools.build import main; main(); --verbose --no-make --qmake /usr/pkg/qt5/bin/qmake
>> Querying qmake about your Qt installation...
>> /usr/pkg/qt5/bin/qmake -query
>> These bindings will be built: pictureflow.
>> Generating the pictureflow bindings...
>> -c: Q_PID is undefined

I son't see where it is used, but it seems to be defined in

/usr/pkg/share/sip3.9/PyQt5/QtCore/qprocess.sip:typedef void *Q_PID;
/usr/pkg/share/sip3.9/PyQt5/QtCore/qprocess.sip:typedef qint64 Q_PID;
/usr/pkg/share/sip3.9/PyQt5/QtCore/qprocess.sip:    Q_PID pid() const;

Moving that file aside gives an error that it isn't found, so it is included
from somewhere.
Commenting out the 3rd line makes the build work.
The first two are conditional defines; 
It seems that %If (WS_X11 || WS_MACX) isn't matching.


Next error:

$ calibre
Traceback (most recent call last):
  File "/usr/pkg/bin/calibre", line 21, in <module>
    sys.exit(calibre())
  File "/usr/pkg/lib/calibre/calibre/gui_launch.py", line 64, in calibre
    main(args)
  File "/usr/pkg/lib/calibre/calibre/gui2/main.py", line 533, in main
    app, opts, args = init_qt(args)
  File "/usr/pkg/lib/calibre/calibre/gui2/main.py", line 124, in init_qt
    app = Application(args, override_program_name=override, windows_app_uid=MAIN_APP_UID)
  File "/usr/pkg/lib/calibre/calibre/gui2/__init__.py", line 915, in __init__
    from calibre_extensions import progress_indicator
RuntimeError: the sip module implements API v12.0 to v12.7 but the progress_indicator module requires API v12.9


Does that mean that py39-qt5 also needs to be built with sip6 somehow?
Or that calibre's use of sip6 needs to be replaced with sip4?
